spring:
  datasource:
    url: jdbc:h2:mem:database;DATABASE_TO_LOWER=TRUE
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    token:
      secret-key: ZG9iYnlpc21ha2luZ2phdmFzcHJpbmdyb29tZXNjYXBlbWVtYmVy
      expire-length: 3600000  # 1시간
